# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pipenv
        pipenv lock
        pipenv install --dev --deploy

    - name: Linter
      run: |
        pipenv run flake8 --exclude=".venv/,.git,__pycache__"

    - name: Testing
      run: |
       pipenv run nose2 --verbose --with-coverage --coverage src
